using System;
using System.Collections.Generic;
using Compositor.KK.Utils;
using DefaultNamespace;
using UnityEngine;

namespace Compositor.KK
{
    /// <summary>
    /// Represents the output of a compositing node within a visual compositing framework.
    /// Encapsulates the output's name, data type, current value, local position relative to the node,
    /// and its connections to other nodes' input ports. This class allows the output to be linked
    /// to multiple other nodes and facilitates data propagation between connected nodes in the graph.
    /// </summary>
    public class NodeOutput
    {
        /// <summary>
        /// Represents the name of the node output.
        /// </summary>
        /// <remarks>
        /// This property specifies the identifier or label for the node output.
        /// It is used to display and distinguish output ports in the user interface
        /// and to associate connections with their corresponding outputs.
        /// </remarks>
        public string Name { get; set; }
        /// <summary>
        /// Specifies the data type of the output generated by the node.
        /// </summary>
        /// <remarks>
        /// This property determines the type of data that the output port can produce or transmit.
        /// It is utilized to ensure compatibility during connections between nodes by
        /// validating whether the receiving input port can accept the output's data type.
        /// </remarks>
        public SocketType OutputType { get; set; }
        /// <summary>
        /// Represents the value of a node output in the compositor graph.
        /// </summary>
        /// <remarks>
        /// This property defines the data or object being output by the node output.
        /// It can hold any object type and is used to transfer information from one
        /// node to another within the compositor system. Changes to this property
        /// should be propagated to connected input nodes to ensure synchronization
        /// across the graph.
        /// </remarks>
        public object Value { get; set; }
        /// <summary>
        /// Represents the collection of connections established by this output port to other nodes' input ports.
        /// </summary>
        /// <remarks>
        /// This property maintains a list of all the connections originating from the output port.
        /// Each connection links the output port to an input port of another node, facilitating data flow
        /// within the compositing system. Connections are dynamically updated as nodes are linked or unlinked.
        /// </remarks>
        public List<NodeConnection> Connections { get; set; }
        /// <summary>
        /// Represents the local position of an output port in the node's coordinate space.
        /// </summary>
        /// <remarks>
        /// This property defines the position of the output port relative to the node's origin.
        /// It is primarily used for graphical rendering and determining interaction points
        /// within the user interface when connecting nodes.
        /// </remarks>
        public Vector2 LocalPosition { get; set; }

        /// <summary>
        /// Represents the output of a compositing node, allowing connections to inputs of other nodes.
        /// Stores metadata about the output such as its name, data type, and positional information
        /// on the node it belongs to, as well as its connections to other nodes.
        /// </summary>
        public NodeOutput(string name, SocketType outputType, Vector2 localPosition)
        {
            Name = name;
            OutputType = outputType;
            LocalPosition = localPosition;
            Connections = new List<NodeConnection>();
        }

        public NodeOutput(string name, SocketType outputType, PortPositioning portMode) : this(name, outputType, Vector2.zero)
        {
            PortMode = portMode;
        }
        
        public PortPositioning PortMode { get; set; } = PortPositioning.Fixed;

        /// <summary>
        /// Specifies the positioning mode for ports in a compositing node framework.
        /// Determines how ports are visually aligned or repositioned within the node's interface,
        /// affecting their layout and interaction within the graphical editor.
        /// </summary>
        [Flags]
        public enum PortPositioning
        {
            Fixed,
            Reposition
        }

        /// <summary>
        /// Sets the value of this output and propagates the updated value to all connected inputs of other nodes.
        /// This ensures that all dependencies are updated to reflect the current state.
        /// </summary>
        /// <param name="value">The new value to assign to the output and propagate to connected nodes as necessary.</param>
        public void SetValue(object value)
        {
            Value = value;

            foreach (var connection in Connections)
            {
                if (connection.InputNode.Inputs.Count > connection.InputIndex)
                {
                    var input = connection.InputNode.Inputs[connection.InputIndex];
                    object convertedValue = value;
                    if (OutputType != input.AcceptedType && value != null)
                    {
                        convertedValue = Converter.FastConvert(OutputType, input.AcceptedType, value as float[]);
                    }

                    connection.InputNode.Inputs[connection.InputIndex].Value = convertedValue;

                    if (connection.InputNode is LazyCompositorNode lazy)
                        lazy.NotifyOutputChanged();
                }
            }
        }
    }
}